### ISSUE TITLE
[WSP-1] Overhaul our WASM build/bundling process

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/wasm-sqlparser#121]
Having the WASM binary wrapped the way we're doing it here is causing issues with various build systems. Let's just figure out what the best state of the art build process is right now for bundling WASM, and just use that to avoid these issues.

<sub>[WSP-1](https://linear.app/tableland/issue/WSP-1/overhaul-our-wasm-buildbundling-process)</sub>

**Comment by dtbuchholz** [comment]
Related to this [Discord comment](https://discord.com/channels/592843512312102924/968582612945870878/1096578239373267024), an example of an error that occurs in the [docs site](https://github.com/tablelandnetwork/docs). If you run `npm run build`, you'll see the following:
```json
[WARNING] {
  "moduleIdentifier": "javascript/dynamic|/Users/dtb/tbl/docs/node_modules/@tableland/sqlparser/cjs/wasm_exec.js",
  "moduleName": "./node_modules/@tableland/sqlparser/cjs/wasm_exec.js",
  "loc": "14:21-28",
  "message": "Critical dependency: require function is used in a way in which dependencies cannot be statically extracted",
  "compilerPath": "server"
}
```
...in case you want something to test against. It doesn't have an impact on the site, to my knowledge, since I barely use the SDK within in, besides importing supported chains. I believe the site uses `webpack@^5.73.0`

**Comment by carsonfarmer** [comment]
Really excited for this fix!

**Comment by joewagner** [comment]
> Really excited for this fix!

The release is planned for tomorrow at 1.3.0
